const stockProductos = [
    {id: 1, nombre: "Mango", cantidad: 1, desc: "1 Und.", precio: 3000, img: './img/mango.jpg'},
    {id: 2, nombre: "Piña", cantidad: 1, desc: "1 Und.", precio: 2500, img: './img/pina.jpg'},
    {id: 3, nombre: "Ajo", cantidad: 1, desc: "45 Gr.", precio: 800, img: './img/ajo.jpg'},
    {id: 4, nombre: "Cebolla Roja", cantidad: 1, desc: "1 Und.", precio: 1300, img: './img/cebolla.jpg'},
    {id: 5, nombre: "Ciruela importada", cantidad: 1, desc: "1 Und.", precio: 1200, img: './img/ciruela.jpg'},
    {id: 6, nombre: "Durazno importado", cantidad: 1, desc: "1 Und.", precio: 1500, img: './img/durazno.jpg'},
    {id: 7, nombre: "Tomate L/vida", cantidad: 1, desc: "1 Und.", precio: 800, img: './img/tomate.jpg'},
    {id: 8, nombre: "Uva Red Globe", cantidad: 1, desc: "1 Und.", precio: 19900, img: './img/uvas.jpg'},
    {id: 9, nombre: "Melon", cantidad: 1, desc: "1 Und.", precio: 10900, img: './img/melon.jpg'},
    {id: 10, nombre: "Naranja tangelo", cantidad: 1, desc: "1 Und.", precio: 1600, img: './img/naranja.jpg'},
    {id: 11, nombre: "Zanahoria", cantidad: 1, desc: "1 Und.", precio: 600, img: './img/zanahoria.jpg'},
    {id: 12, nombre: "Limón", cantidad: 1, desc: "1 Und.", precio: 500, img: './img/limon.jpg'},
    {id: 13, nombre: "Lima", cantidad: 1, desc: "1 Und.", precio: 450, img: './img/Lima.jpg'},
    {id: 14, nombre: "Pera nacional", cantidad: 1, desc: "1 Und.", precio: 2400, img: './img/pera.jpg'},
    {id: 15, nombre: "Lechuga batavia", cantidad: 1, desc: "1 Und.", precio: 1900, img: './img/lechuga.jpg'},
    {id: 16, nombre: "Banano", cantidad: 1, desc: "1 Und.", precio: 600, img: './img/banano.jpg'},
    {id: 17, nombre: "Aguacate", cantidad: 1, desc: "1 Und.", precio: 2700, img: './img/aguacate.jpg'},
    {id: 18, nombre: "Manzana", cantidad: 1, desc: "1 Und.", precio: 1800, img: './img/manzana.jpg'},
    {id: 19, nombre: "Pepino", cantidad: 1, desc: "1 Und.", precio: 950, img: './img/pepino.jpg'},
    {id: 20, nombre: "Kiwi", cantidad: 1, desc: "1 Und.", precio: 1350, img: './img/kiwi.jpg'},
]